name: Compiling-TeX-Article
on:
  push:
    branches:
      - no-main
      - 01-ci
      - 03-distillation
      - 07-reviews
      - 09-arxiv-v01
      - adds-branch-name

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-article]') && !contains(github.event.head_commit.message, '[skip-all]')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile Article
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: article/tex

    - name: Check pdf files
      run: |
        file article/tex/main.pdf | grep -q ' PDF '
 
    - name: Upload
      run: |
        # configure git
        git config --global user.name "mxochicale"
        git config --global user.email "perez.xochicale@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch pdfs git@github.com:air4children/hri2021.git "$GITHUB_WORKSPACE/deploy"
        cp -f article/tex/main.pdf "$GITHUB_WORKSPACE/deploy/article.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add article.pdf 
        git commit -m "latex-action deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
